#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
set -x

# Apply migrations
alembic upgrade head

# Run Uvicorn server using ASGI
uvicorn app:create_app --proxy-headers --workers=2 --loop uvloop --http httptools --host 0.0.0.0 --port 8000 --reload
