name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.7.2"
  UV_LINK_MODE: "copy"
  ENV: "ci"
  POSTGRES_DB: "test"
  POSTGRES_USER: "test"
  POSTGRES_PASSWORD: "test"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ruff:
    name: lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set derived env (IMAGE_*, UV_CACHE_DIR)
        run: |
          echo "IMAGE_PYTHON=python:${PYTHON_VERSION}-slim" >> $GITHUB_ENV
          echo "IMAGE_UV=ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-bookworm-slim" >> $GITHUB_ENV
          echo "UV_CACHE_DIR=${UV_CACHE_DIR:-$HOME/.cache/uv}" >> $GITHUB_ENV

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ hashFiles('uv.lock') }}
          restore-keys: uv-

      - name: Install uv
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          curl -LsSf "https://astral.sh/uv/${UV_VERSION}/install.sh" | sh
          export PATH="$HOME/.local/bin:$PATH"
          uv tool install go-task-bin || true

      - name: Run linter
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          RUNNER="uv run" task lint

  mypy:
    name: typecheck (mypy)
    runs-on: ubuntu-latest
    needs: ruff
    steps:
      - uses: actions/checkout@v4

      - name: Set derived env
        run: |
          echo "IMAGE_PYTHON=python:${PYTHON_VERSION}-slim" >> $GITHUB_ENV
          echo "IMAGE_UV=ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-bookworm-slim" >> $GITHUB_ENV
          echo "UV_CACHE_DIR=${UV_CACHE_DIR:-$HOME/.cache/uv}" >> $GITHUB_ENV

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ hashFiles('uv.lock') }}
          restore-keys: uv-

      - name: Install uv
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          curl -LsSf "https://astral.sh/uv/${UV_VERSION}/install.sh" | sh
          export PATH="$HOME/.local/bin:$PATH"
          uv tool install go-task-bin || true

      - name: Run typecheck
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          RUNNER="uv run" task typecheck

  pytest:
    name: tests (pytest)
    runs-on: ubuntu-latest
    needs: mypy
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: "test"
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: "test"
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test -d test"
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Postgres
        run: |
          for i in $(seq 1 30); do
            pg_isready -h localhost -p 5432 -U test && break
            sleep 1
          done

      - name: Set derived env
        run: |
          echo "IMAGE_PYTHON=python:${PYTHON_VERSION}-slim" >> $GITHUB_ENV
          echo "UV_CACHE_DIR=${UV_CACHE_DIR:-$HOME/.cache/uv}" >> $GITHUB_ENV

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ hashFiles('uv.lock') }}
          restore-keys: uv-

      - name: Install uv
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          curl -LsSf "https://astral.sh/uv/${UV_VERSION}/install.sh" | sh
          export PATH="$HOME/.local/bin:$PATH"
          uv tool install go-task-bin || true

      - name: Run tests
        env:
          DATABASE_URL: "postgresql://test:test@localhost:5432/test"
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          RUNNER="uv run" task test-ci

  build-image:
    name: build & push image
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          curl -LsSf "https://astral.sh/uv/${UV_VERSION}/install.sh" | sh
          export PATH="$HOME/.local/bin:$PATH"
          uv tool install go-task-bin || true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: deployments/compose/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Print pushed tags
        run: |
          echo "Pushed tags:"
          echo "${{ steps.meta.outputs.tags }}"
